Restore "module_apex_set" from removed soong_config_module_types
Required for building mainline(GPSU) from source. Without this, we get:
error: <input>: module type "module_apex_set" not defined in "packages/modules/common/Android.bp"
error: vendor/partner_modules/DynamicCommonLibrariesPrebuilt/Android.bp:36:1: unrecognized module type "module_apex_set"
error: vendor/partner_modules/DynamicCommonLibrariesPrebuilt/Android.bp:43:1: unrecognized module type "module_apex_set"
fatal errors encountered

Change-Id: Ibc678351e70b868dcb5a7e7cb982c00dfe890035